### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nf1213** [nf1213/blog#1]
- [x] Have users and authorization
- [x] Have comments
- [x] Have comments on same page
- [x] Deploy
- [x] Upload pictures to posts
- [x] Tests
- [x] Automatically add instagram posts
- [ ] Allow markdown in posts
- [ ] Use online photo storage
- [ ] Add twitter
- [ ] Make an android app that lets you blog
- [ ] YouTube
- [ ] Infinite scroll
